### ISSUE TITLE
Project Review: Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [tatemdomina/teacozy#1]
Rubric Score Skeleton
### Criteria 1: HTML Structure  
* _Score Level:_ 4/4
* _Comment(s):_ Nice work with your HTML overall. All of the elements are used appropriately, classes and id's look good/descriptive, `alt` attribute descriptions were included, and the structure is spot on 👍 . The only recommendation for improvement I have here is to make sure you wire up the navigation links in the header to the respective sections of the site by taking advantage of the `href` attribute.
 
### Criteria 2: Visual Layout
* _Score Level:_ 3.5/4
* _Comment(s):_ The overall layout of the page is just about spot on with respect to the design specification. The only section that looks slightly off is the locations section, where the entire section takes up the whole width of the page, instead of having space on both sides.
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4/4
* _Comment(s):_ Your use of flexbox throughout the project is great! All of the items throughout the sections are grouped together appropriately.
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 4/4
* _Comment(s):_ All of the appropriate styles and content (fonts, colors, images, etc) were included and used in the appropriate sections 👍

**Comment by tatemdomina** [comment]
Thanks, Sid!
